Repository grafana/metrics-drilldown, pull requests merged in 2025-09, with the labels that each got.

#670 refactor(*): Cleanup unused variables + related refactorings
  src/Breakdown/MetricLabelValuesList/AddToFiltersGraphAction.tsx
  src/DataTrail.test.tsx
  src/DataTrail.tsx
  src/MetricScene.tsx
  src/bookmarks/genBookmarkKey.ts
  src/utils.test.ts
  src/utils.ts
Labels: refactor

#672 refactor(*): Refactor MetricLabelValuesList and other small ones
  src/Breakdown/MetricLabelValuesList/MetricLabelValuesList.tsx
  src/Breakdown/MetricLabelsList/MetricLabelsList.tsx
  src/GmdVizPanel/GmdVizPanel.tsx
  src/GmdVizPanel/types/timeseries/addCardinalityInfo.ts
  src/GmdVizPanel/types/timeseries/behaviors/addCardinalityInfo.ts
  src/GmdVizPanel/types/timeseries/buildTimeseriesPanel.ts
  src/GmdVizPanel/types/timeseries/transformations/addRefId.ts
  src/GmdVizPanel/types/timeseries/transformations/addUnspecifiedLabel.ts
  src/GmdVizPanel/types/timeseries/transformations/sliceSeries.ts
  src/MetricActionBar.tsx
  src/MetricGraphScene.tsx
Labels: refactor

#674 fix(RelatedLogs): Fix fatal error when no logs are found
  e2e/tests/metric-scene-view.spec.ts
  src/RelatedLogs/RelatedLogsScene.tsx
Labels: fix

#676 perf(GmdVizPanel): Faster first render + small refatorings
  src/DataTrail.tsx
  src/GmdVizPanel/GmdVizPanel.tsx
  src/GmdVizPanel/components/ConfigurePanelForm/ConfigurePanelForm.tsx
  src/GmdVizPanel/config/presets/getConfigPresetsForMetric.ts
  src/GmdVizPanel/matchers/__tests__/isCounterMetric.test.ts
  src/GmdVizPanel/matchers/__tests__/isStatusUpDownMetric.test.ts
  src/GmdVizPanel/matchers/getMetricType.ts
  src/GmdVizPanel/matchers/getPanelTypeForMetric.ts
  src/GmdVizPanel/matchers/isClassicHistogramMetric.ts
  src/GmdVizPanel/matchers/isCounterMetric.ts
  src/GmdVizPanel/matchers/isHistogramMetric.ts
  src/GmdVizPanel/matchers/isStatusUpDownMetric.ts
  src/MetricGraphScene.tsx
  src/helpers/MetricDatasourceHelper.ts
Labels: perf

#679 fix(Breakdown): Remove "le label from options
  src/Breakdown/GroupByVariable.tsx
Labels: fix

#691 fix(DataTrail): Set URL search parameters namespace when the app/components are embedded
  src/utils.ts
Labels: fix

#699 fix(Docker): Fix GRAFANA_IMAGE env var used in playwright
  docker-compose.yaml
Labels: ❤️‍🩹 bug, fix

#701 chore: fallback grafana version in playwright screenshots
  e2e/config/playwright.config.common.ts
Labels: chore

#700 refactor(GroupByLabel): Removing code!
  src/WingmanDataTrail/GroupBy/MetricsGroupByRow.tsx
  src/WingmanDataTrail/GroupBy/MetricsWithLabelValue/MetricsWithLabelValueDataSource.ts
  src/WingmanDataTrail/GroupBy/MetricsWithLabelValue/MetricsWithLabelValueVariable.ts
  src/WingmanDataTrail/MetricsReducer.tsx
  src/WingmanDataTrail/MetricsVariables/MetricsVariable.ts
  src/WingmanDataTrail/SideBar/sections/LabelsBrowser/LabelsBrowser.tsx
  src/WingmanDataTrail/helpers/isPrometheusRule.ts
Labels: refactor

#708 chore: bump version v1.0.14 correctly
  CHANGELOG.md
  package-lock.json
  package.json
Labels: chore

#704 chore: related metrics sticky search - implement fast follow feedback
  e2e/fixtures/components/AppControls.ts
  src/MetricActionBar.tsx
  src/MetricGraphScene.tsx
  src/types.ts
Labels: chore

#710 fix: look for const to render copy url menu item
  src/Menu/PanelMenu.tsx
Labels: fix

#636 chore: use template variables fast follow
  package-lock.json
  package.json
  src/extensions/links.test.ts
  src/extensions/links.ts
Labels: chore

#716 test: e2e test for panel menu
  e2e/fixtures/views/MetricSceneView.ts
  e2e/tests/metric-scene-view.spec.ts
  src/Menu/PanelMenu.tsx
  src/MetricGraphScene.tsx
Labels: test

#665 refactor(links): lazy load lezer parser in links, reduce bundle size
  src/WingmanDataTrail/ListControls/MetricsSorter/fetchers/fetchAlertingMetrics.ts
  src/WingmanDataTrail/ListControls/MetricsSorter/fetchers/fetchDashboardMetrics.ts
  src/exposedComponents/LabelBreakdown/LabelBreakdown.tsx
  src/extensions/links.test.ts
  src/extensions/links.ts
  src/utils/utils.promql.ts
Labels: refactor

#718 chore(*): Group MetricScene files together
  src/DataTrail.test.tsx
  src/DataTrail.tsx
  src/Integrations/logs/labelsCrossReference.test.ts
  src/MetricScene/Breakdown/GroupBySelector/GroupBySelector.tsx
  src/MetricScene/Breakdown/GroupByVariable.tsx
  src/MetricScene/Breakdown/LabelBreakdownScene.tsx
  src/MetricScene/Breakdown/MetricLabelValuesList/AddToFiltersGraphAction.tsx
  src/MetricScene/Breakdown/MetricLabelValuesList/LabelValuesCountProvider.ts
  src/MetricScene/Breakdown/MetricLabelValuesList/MetricLabelValuesList.tsx
  src/MetricScene/Breakdown/MetricLabelValuesList/SceneByFrameRepeater.tsx
  src/MetricScene/Breakdown/MetricLabelValuesList/SortBySelector.tsx
  src/MetricScene/Breakdown/MetricLabelValuesList/getLabelValueFromDataFrame.ts
  src/MetricScene/Breakdown/MetricLabelsList/MetricLabelsList.tsx
  src/MetricScene/Breakdown/MetricLabelsList/SelectLabelAction.tsx
  src/MetricScene/Breakdown/MetricLabelsList/behaviors/publishTimeseriesData.ts
  src/MetricScene/Breakdown/MetricLabelsList/behaviors/syncYAxis.ts
  src/MetricScene/Breakdown/MetricLabelsList/events/EventForceSyncYAxis.ts
  src/MetricScene/Breakdown/MetricLabelsList/events/EventResetSyncYAxis.ts
  src/MetricScene/Breakdown/MetricLabelsList/events/EventTimeseriesDataReceived.ts
  src/MetricScene/MetricActionBar.tsx
  src/MetricScene/MetricGraphScene.tsx
  src/MetricScene/MetricScene.tsx
  src/MetricScene/PanelMenu/PanelMenu.tsx
  src/MetricScene/PanelMenu/actions/CopyUrlAction.ts
  src/MetricScene/PanelMenu/actions/ExploreAction.ts
  src/MetricScene/PanelMenu/actions/investigation/AddToExplorationsButton.test.tsx
  src/MetricScene/PanelMenu/actions/investigation/AddToExplorationsButton.tsx
  src/MetricScene/PanelMenu/actions/investigation/InvestigationAction.ts
  src/MetricScene/RelatedLogs/NoRelatedLogsFound.tsx
  src/MetricScene/RelatedLogs/OpenInLogsDrilldownButton.tsx
  src/MetricScene/RelatedLogs/RelatedLogsOrchestrator.ts
  src/MetricScene/RelatedLogs/RelatedLogsScene.tsx
  src/MetricScene/RelatedMetrics/PrefixFilterDropdown.tsx
  src/MetricScene/RelatedMetrics/RelatedListControls.tsx
  src/MetricScene/RelatedMetrics/RelatedMetricsScene.tsx
  src/MetricScene/RelatedMetrics/sortRelatedMetrics.ts
  src/WingmanDataTrail/MetricsVariables/MetricsVariableSortEngine.ts
  src/interactions.ts
Labels: chore

#726 chore(Dependencies): Update Grafana packages to 12.2.0
  package-lock.json
  package.json
Labels: chore

#727 chore(Scenes): Upgrade Scenes to v6.39.0
  package-lock.json
Labels: chore

#728 feat: custom values appear first in label filters
  package-lock.json
  package.json
Labels: feat

#733 chore: revert use metadata to distinguish metric type
  e2e/tests/metrics-reducer/metrics-reducer-panel-types.spec.ts-snapshots/11-6-5-metric-list-with-all-types-chromium-linux.png
  e2e/tests/metrics-reducer/metrics-reducer-panel-types.spec.ts-snapshots/12-0-3-metric-list-with-all-types-chromium-linux.png
  e2e/tests/metrics-reducer/metrics-reducer-panel-types.spec.ts-snapshots/12-1-1-metric-list-with-all-types-chromium-linux.png
  e2e/tests/metrics-reducer/metrics-reducer-view.spec.ts
  e2e/tests/metrics-reducer/metrics-reducer-view.spec.ts-snapshots/11-6-6-metrics-reducer-group-by-label-after-select-chromium-linux.png
  e2e/tests/metrics-reducer/metrics-reducer-view.spec.ts-snapshots/11-6-6-metrics-reducer-group-by-label-chromium-linux.png
  e2e/tests/metrics-reducer/metrics-reducer-view.spec.ts-snapshots/12-0-5-metrics-reducer-group-by-label-after-select-chromium-linux.png
  e2e/tests/metrics-reducer/metrics-reducer-view.spec.ts-snapshots/12-0-5-metrics-reducer-group-by-label-chromium-linux.png
  e2e/tests/metrics-reducer/metrics-reducer-view.spec.ts-snapshots/12-1-2-metrics-reducer-group-by-label-after-select-chromium-linux.png
  e2e/tests/metrics-reducer/metrics-reducer-view.spec.ts-snapshots/12-1-2-metrics-reducer-group-by-label-chromium-linux.png
  e2e/tests/metrics-reducer/metrics-reducer-view.spec.ts-snapshots/12-2-0-metrics-reducer-group-by-label-after-select-chromium-linux.png
  e2e/tests/metrics-reducer/metrics-reducer-view.spec.ts-snapshots/12-2-0-metrics-reducer-group-by-label-chromium-linux.png
  e2e/tests/metrics-reducer/metrics-reducer-view.spec.ts-snapshots/metrics-reducer-group-by-label-after-clear-filter-chromium-linux.png
  e2e/tests/metrics-reducer/metrics-reducer-view.spec.ts-snapshots/metrics-reducer-group-by-label-after-select-chromium-linux.png
  e2e/tests/metrics-reducer/metrics-reducer-view.spec.ts-snapshots/metrics-reducer-group-by-label-chromium-linux.png
  e2e/tests/scopes.spec.ts-snapshots/12-1-1-metric-list-scopes-filters-applied-chromium-linux.png
  src/shared/GmdVizPanel/matchers/isCounterFromMetadata.ts
  src/shared/GmdVizPanel/types/timeseries/__tests__/getTimeseriesQueryRunnerParams.test.ts
  src/shared/GmdVizPanel/types/timeseries/buildTimeseriesPanel.ts
  src/shared/GmdVizPanel/types/timeseries/getTimeseriesQueryRunnerParams.ts
Labels: chore

#572 feat: DataSource Configuration Extensions
  package-lock.json
  src/extensions/datasourceConfigLinks.test.ts
  src/extensions/datasourceConfigLinks.ts
  src/extensions/links.ts
  src/module.tsx
  src/plugin.json
Labels: feat

#730 refactor(GmdVizPanel): Centralize how panels and queries are built
  src/MetricScene/MetricGraphScene.tsx
  src/shared/GmdVizPanel/GmdVizPanel.tsx
  src/shared/GmdVizPanel/components/BookmarkHeaderAction.tsx
  src/shared/GmdVizPanel/components/GmdVizPanelVariantSelector.tsx
  src/shared/GmdVizPanel/types/heatmap/__tests__/getHeatmapQueryRunnerParams.test.ts
  src/shared/GmdVizPanel/types/heatmap/buildHeatmapPanel.ts
  src/shared/GmdVizPanel/types/heatmap/getHeatmapQueryRunnerParams.ts
  src/shared/GmdVizPanel/types/panelBuilder.ts
  src/shared/GmdVizPanel/types/percentiles/buildPercentilesPanel.ts
  src/shared/GmdVizPanel/types/percentiles/getPercentilesQueryRunnerParams.ts
  src/shared/GmdVizPanel/types/stat/buildStatPanel.ts
  src/shared/GmdVizPanel/types/stat/getStatQueryRunnerParams.ts
  src/shared/GmdVizPanel/types/statushistory/buildStatushistoryPanel.ts
  src/shared/GmdVizPanel/types/statushistory/getStatushistoryQueryRunnerParams.ts
  src/shared/GmdVizPanel/types/timeseries/buildTimeseriesPanel.ts
  src/shared/GmdVizPanel/types/timeseries/getTimeseriesQueryRunnerParams.ts
Labels: refactor

#741 fix(MetricDatasourceHelper): Fix cache refresh when changing data source
  src/AppDataTrail/DataTrail.tsx
  src/AppDataTrail/MetricDatasourceHelper/MetricDatasourceHelper.ts
Labels: fix

#723 feat(GmdVizPanel): Always consider the metric metadata to render the proper panel type
  e2e/tests/metrics-reducer/metrics-reducer-panel-types.spec.ts-snapshots/11-6-6-metric-list-after-configure-histograms-chromium-linux.png
  e2e/tests/metrics-reducer/metrics-reducer-panel-types.spec.ts-snapshots/12-0-5-metric-list-after-configure-histograms-chromium-linux.png
  e2e/tests/metrics-reducer/metrics-reducer-panel-types.spec.ts-snapshots/12-1-2-metric-list-after-configure-histograms-chromium-linux.png
  e2e/tests/metrics-reducer/metrics-reducer-panel-types.spec.ts-snapshots/12-2-0-metric-list-after-configure-histograms-chromium-linux.png
  e2e/tests/metrics-reducer/metrics-reducer-view.spec.ts-snapshots/11-6-6-metrics-reducer-group-by-label-after-select-chromium-linux.png
  e2e/tests/metrics-reducer/metrics-reducer-view.spec.ts-snapshots/11-6-6-metrics-reducer-group-by-label-chromium-linux.png
  e2e/tests/metrics-reducer/metrics-reducer-view.spec.ts-snapshots/12-0-5-metrics-reducer-group-by-label-after-select-chromium-linux.png
  e2e/tests/metrics-reducer/metrics-reducer-view.spec.ts-snapshots/12-0-5-metrics-reducer-group-by-label-chromium-linux.png
  e2e/tests/metrics-reducer/metrics-reducer-view.spec.ts-snapshots/12-1-2-metrics-reducer-group-by-label-after-select-chromium-linux.png
  e2e/tests/metrics-reducer/metrics-reducer-view.spec.ts-snapshots/12-2-0-metrics-reducer-group-by-label-chromium-linux.png
  src/AppDataTrail/DataTrail.tsx
  src/AppDataTrail/MetricDatasourceHelper/MetricDatasourceHelper.test.ts
  src/AppDataTrail/MetricDatasourceHelper/MetricDatasourceHelper.ts
  src/MetricScene/Breakdown/LabelBreakdownScene.tsx
  src/MetricScene/Breakdown/MetricLabelValuesList/MetricLabelValuesList.tsx
  src/MetricScene/Breakdown/MetricLabelsList/MetricLabelsList.tsx
  src/MetricScene/MetricGraphScene.tsx
  src/MetricsReducer/MetricsGroupByList/MetricsGroupByRow.tsx
  src/MetricsReducer/MetricsList/MetricsList.tsx
  src/shared/GmdVizPanel/GmdVizPanel.tsx
  src/shared/GmdVizPanel/__tests__/buildQueryExpression.test.ts
  src/shared/GmdVizPanel/behaviors/extremeValueFilterBehavior/extremeValueFilterBehavior.tsx
  src/shared/GmdVizPanel/buildQueryExpression.ts
  src/shared/GmdVizPanel/components/ConfigurePanelAction.tsx
  src/shared/GmdVizPanel/components/ConfigurePanelForm/ConfigurePanelForm.tsx
  src/shared/GmdVizPanel/components/ConfigurePanelForm/EventApplyPanelConfig.ts
  src/shared/GmdVizPanel/components/ConfigurePanelForm/EventCancelConfigurePanel.ts
  src/shared/GmdVizPanel/components/EventConfigurePanel.ts
  src/shared/GmdVizPanel/matchers/getMetricType.ts
  src/shared/GmdVizPanel/matchers/getPanelTypeForMetric.ts
  src/shared/GmdVizPanel/matchers/isCounterFromMetadata.ts
  src/shared/GmdVizPanel/types/heatmap/__tests__/getHeatmapQueryRunnerParams.test.ts
  src/shared/GmdVizPanel/types/heatmap/buildHeatmapPanel.ts
  src/shared/GmdVizPanel/types/heatmap/getHeatmapQueryRunnerParams.ts
  src/shared/GmdVizPanel/types/panelBuilder.ts
  src/shared/GmdVizPanel/types/percentiles/__tests__/getPercentilesQueryRunnerParams.test.ts
  src/shared/GmdVizPanel/types/percentiles/buildPercentilesPanel.ts
  src/shared/GmdVizPanel/types/percentiles/getPercentilesQueryRunnerParams.ts
  src/shared/GmdVizPanel/types/stat/__tests__/getStatQueryRunnerParams.test.ts
  src/shared/GmdVizPanel/types/stat/getStatQueryRunnerParams.ts
  src/shared/GmdVizPanel/types/statushistory/__tests__/getStatushistoryQueryRunnerParams.test.ts
  src/shared/GmdVizPanel/types/statushistory/getStatushistoryQueryRunnerParams.ts
  src/shared/GmdVizPanel/types/timeseries/__tests__/getTimeseriesQueryRunnerParams.test.ts
  src/shared/GmdVizPanel/types/timeseries/behaviors/updateColorsWhenQueriesChange.ts
  src/shared/GmdVizPanel/types/timeseries/buildTimeseriesPanel.ts
  src/shared/GmdVizPanel/types/timeseries/getTimeseriesQueryRunnerParams.ts
Labels: feat

#745 feat(Breakdown): Disable __ignore_usage__ label for the main query
  src/MetricScene/Breakdown/MetricLabelValuesList/MetricLabelValuesList.tsx
Labels: feat

#744 feat(*): Introduce presets for "_info" metrics
  e2e/tests/metrics-reducer/metrics-reducer-view.spec.ts-snapshots/11-6-6-sidebar-prefixes-selected-metric-counts-chromium-linux.png
  e2e/tests/metrics-reducer/metrics-reducer-view.spec.ts-snapshots/12-0-5-sidebar-prefixes-selected-metric-counts-chromium-linux.png
  e2e/tests/metrics-reducer/metrics-reducer-view.spec.ts-snapshots/12-1-2-sidebar-prefixes-selected-metric-counts-chromium-linux.png
  e2e/tests/metrics-reducer/metrics-reducer-view.spec.ts-snapshots/12-2-0-sidebar-prefixes-selected-metric-counts-chromium-linux.png
  src/shared/GmdVizPanel/config/presets/config-presets-infos.ts
  src/shared/GmdVizPanel/config/presets/getConfigPresetsForMetric.ts
  src/shared/GmdVizPanel/config/presets/types.ts
  src/shared/GmdVizPanel/config/promql-functions.ts
  src/shared/GmdVizPanel/matchers/getMetricType.ts
  src/shared/GmdVizPanel/matchers/isInfoMetric.ts
  src/shared/GmdVizPanel/types/timeseries/getTimeseriesQueryRunnerParams.ts
Labels: feat
