Repository grafana/metrics-drilldown, pull requests merged in 2025-07, with the labels that each got.

#538 fix: exclude dubious errors from error boundary
  src/App/useCatchExceptions.test.ts
  src/App/useCatchExceptions.ts
Labels: fix

#535 feat: preserve labels and time range for logs drilldown
  docker-compose.yaml
  src/RelatedLogs/OpenInLogsDrilldownButton.tsx
  src/RelatedLogs/RelatedLogsOrchestrator.ts
  src/RelatedLogs/RelatedLogsScene.tsx
  src/plugin.json
Labels: feat

#543 chore: prepare for removal of deprecated method
  src/helpers/MetricDatasourceHelper.ts
Labels: chore

#544 fix: CVE-2025-5889
  jest.config.js
  package-lock.json
  src/helpers/MetricDatasourceHelper.ts
  src/mocks/datasource.ts
Labels: fix

#539 feat(ExtensionPoint): Add link for Grafana assistant to build URL
  src/extensions/links.test.ts
  src/extensions/links.ts
  src/plugin.json
Labels: ✨ enhancement, :potted_plant: increase adoption/consumption, feat

#547 chore: bump version to v1.0.6
  CHANGELOG.md
  package-lock.json
  package.json
Labels: chore

#542 refactor: use promql parser to build links
  package-lock.json
  package.json
  src/extensions/links.test.ts
  src/extensions/links.ts
Labels: refactor

#554 ci: add Grafana instance with Scopes enabled
  docker-compose.yaml
Labels: ci

#555 fix(MetricScene): After sorting, timeseries should sync their y-axis
  e2e/fixtures/views/MetricSceneView.ts
  e2e/fixtures/views/MetricsReducerView.ts
  e2e/tests/metric-scene-view.spec.ts
  e2e/tests/metric-scene-view.spec.ts-snapshots/metric-scene-breakdown-label-quicksearch-panels-list-chromium-linux.png
  e2e/tests/metric-scene-view.spec.ts-snapshots/metric-scene-breakdown-label-sort-alpha-a-z-panels-list-chromium-linux.png
  e2e/tests/metric-scene-view.spec.ts-snapshots/metric-scene-breakdown-label-sort-alpha-z-a-panels-list-chromium-linux.png
  e2e/tests/metric-scene-view.spec.ts-snapshots/metric-scene-breakdown-label-sort-outlying-panels-list-chromium-linux.png
  src/Breakdown/BreakdownSearchScene.tsx
  src/Breakdown/LabelBreakdownScene.tsx
  src/Breakdown/SortByScene.tsx
  src/services/sorting.ts
Labels: fix

#556 refactor(MetricScene): Introduce the new GroupByVariable
  e2e/fixtures/views/MetricSceneView.ts
  src/Breakdown/AddToFiltersGraphAction.tsx
  src/Breakdown/GroupByVariable.tsx
  src/Breakdown/LabelBreakdownScene.tsx
  src/Breakdown/MetricLabelsList/LabelVizPanel.tsx
  src/Breakdown/SelectLabelAction.tsx
  src/Breakdown/utils.ts
  src/BreakdownLabelSelector.tsx
  src/DataTrail.tsx
  src/MetricScene.tsx
  src/StatusWrapper.tsx
  src/interactions.ts
  src/utils.ts
Labels: refactor

#560 refactor(QuickSearch): Decouple QuickSearch from metric variables
  src/RelatedMetricsScene/RelatedListControls.tsx
  src/WingmanDataTrail/ListControls/ListControls.tsx
  src/WingmanDataTrail/ListControls/QuickSearch/CountsProvider/CountsProvider.ts
  src/WingmanDataTrail/ListControls/QuickSearch/CountsProvider/MetricVariableCountsProvider.ts
  src/WingmanDataTrail/ListControls/QuickSearch/QuickSearch.tsx
Labels: refactor

#561 chore: bump version v1.0.7
  CHANGELOG.md
  package-lock.json
  package.json
Labels: chore

#557 perf(MetricScene): Add pagination after selecting a label (+ various refactorings)
  e2e/fixtures/views/MetricSceneView.ts
  e2e/tests/metric-scene-view.spec.ts
  e2e/tests/metric-scene-view.spec.ts-snapshots/metric-scene-breakdown-label-quicksearch-panels-list-chromium-linux.png
  e2e/tests/metric-scene-view.spec.ts-snapshots/metric-scene-breakdown-label-single-panel-chromium-linux.png
  src/Breakdown/BreakdownSearchScene.tsx
  src/Breakdown/ByFrameRepeater.tsx
  src/Breakdown/LabelBreakdownScene.tsx
  src/Breakdown/LayoutSwitcher.tsx
  src/Breakdown/MetricLabelValuesList/AddToFiltersGraphAction.tsx
  src/Breakdown/MetricLabelValuesList/LabelValuesCountProvider.ts
  src/Breakdown/MetricLabelValuesList/MetricLabelsValuesList.tsx
  src/Breakdown/MetricLabelValuesList/SceneByFrameRepeater.tsx
  src/Breakdown/MetricLabelValuesList/SortBySelector.tsx
  src/Breakdown/MetricLabelValuesList/getLabelValueFromDataFrame.ts
  src/Breakdown/MetricLabelsList/LabelVizPanel.tsx
  src/Breakdown/MetricLabelsList/MetricLabelsList.tsx
  src/Breakdown/MetricLabelsList/SelectLabelAction.tsx
  src/Breakdown/MetricLabelsList/behaviors/publishTimeseriesData.ts
  src/Breakdown/MetricLabelsList/behaviors/syncYAxis.ts
  src/Breakdown/MetricLabelsList/events/EventForceSyncYAxis.ts
  src/Breakdown/MetricLabelsList/events/EventResetSyncYAxis.ts
  src/Breakdown/MetricLabelsList/transformations/addUnspecifiedLabel.ts
  src/Breakdown/SearchInput.tsx
  src/Breakdown/SortByScene.tsx
  src/Breakdown/panelConfigs.ts
  src/Breakdown/types.test.ts
  src/Breakdown/types.ts
  src/Breakdown/utils.ts
  src/Breakdown/yAxisSyncBehavior.ts
  src/MetricActionBar.tsx
  src/interactions.ts
  src/services/search.ts
  src/services/store.ts
Labels: perf

#558 feat: expose embedded label breakdown component
  e2e/tests/metrics-reducer-view.spec.ts-snapshots/sidebar-prefixes-and-suffixes-selected-metric-counts-chromium-linux.png
  e2e/tests/metrics-reducer-view.spec.ts-snapshots/sidebar-prefixes-selected-metric-counts-chromium-linux.png
  package-lock.json
  package.json
  src/App/Routes.tsx
  src/DataTrail.tsx
  src/Integrations/SceneDrawer.tsx
  src/MetricActionBar.tsx
  src/MetricGraphScene.tsx
  src/MetricScene.tsx
  src/exposedComponents/LabelBreakdown/LabelBreakdown.tsx
  src/exposedComponents/LabelBreakdown/LazyLabelBreakdown.tsx
  src/exposedComponents/LabelBreakdown/config.ts
  src/exposedComponents/components.ts
  src/module.tsx
  src/pages/TrailWingman.tsx
  src/plugin.json
  src/utils.ts
  src/utils/utils.styles.ts
Labels: feat

#576 perf(*): Prevent duplicated "metrics list" queries when landing on the page
  src/DataTrail.tsx
  src/WingmanDataTrail/MetricsVariables/FilteredMetricsVariable.ts
Labels: perf

#574 fix(MetricsReducer): Fix zero count when coming back from the MetricScene
  src/Breakdown/MetricLabelValuesList/LabelValuesCountProvider.ts
  src/RelatedMetricsScene/RelatedListControls.tsx
  src/WingmanDataTrail/ListControls/ListControls.tsx
  src/WingmanDataTrail/ListControls/QuickSearch/CountsProvider/MetricVariableCountsProvider.ts
Labels: fix

#588 feat(RelatedLogs): Add spinner while loading
  src/RelatedLogs/RelatedLogsScene.tsx
Labels: feat

#568 chore: add tracking for opening in embedded mode
  src/exposedComponents/LabelBreakdown/LabelBreakdown.tsx
  src/exposedComponents/LabelBreakdown/config.ts
  src/exposedComponents/components.ts
  src/interactions.ts
  src/utils/utils.types.ts
Labels: chore

#565 test(EndToEnd): Support multiple Grafana versions for screenshot testing
  .env.example
  docker-compose.yaml
  docs/end-to-end-testing.md
  e2e/config/grafana-versions-supported.ts
  e2e/config/playwright.config.common.ts
  e2e/fixtures/components/Sidebar.ts
  e2e/fixtures/index.ts
  e2e/fixtures/views/MetricSceneView.ts
  e2e/fixtures/views/MetricsReducerView.ts
  e2e/tests/metric-scene-view.spec.ts
  e2e/tests/metric-scene-view.spec.ts-snapshots/11-6-4-metric-scene-breakdown-all-panels-list-chromium-linux.png
  e2e/tests/metric-scene-view.spec.ts-snapshots/12-0-3-metric-scene-breakdown-all-panels-list-chromium-linux.png
  e2e/tests/metric-scene-view.spec.ts-snapshots/12-1-0-metric-scene-breakdown-all-panels-list-chromium-linux.png
  e2e/tests/metric-scene-view.spec.ts-snapshots/metric-scene-breakdown-all-panels-list-chromium-linux.png
  e2e/tests/metric-scene-view.spec.ts-snapshots/metric-scene-breakdown-label-quicksearch-panels-list-chromium-linux.png
  e2e/tests/metric-scene-view.spec.ts-snapshots/metric-scene-breakdown-label-sort-alpha-a-z-panels-list-chromium-linux.png
  e2e/tests/metric-scene-view.spec.ts-snapshots/metric-scene-breakdown-label-sort-outlying-panels-list-chromium-linux.png
  e2e/tests/metric-scene-view.spec.ts-snapshots/metric-scene-main-viz-chromium-linux.png
  e2e/tests/metric-scene-view.spec.ts-snapshots/metric-scene-related-metrics-all-list-chromium-linux.png
  e2e/tests/metric-scene-view.spec.ts-snapshots/metric-scene-related-metrics-prefix-filtered-list-chromium-linux.png
  e2e/tests/metrics-reducer-view.spec.ts
  e2e/tests/metrics-reducer-view.spec.ts-snapshots/11-6-4-sidebar-prefixes-and-suffixes-selected-metric-counts-chromium-linux.png
  e2e/tests/metrics-reducer-view.spec.ts-snapshots/11-6-4-sidebar-prefixes-selected-metric-counts-chromium-linux.png
  e2e/tests/metrics-reducer-view.spec.ts-snapshots/12-0-3-sidebar-prefixes-and-suffixes-selected-metric-counts-chromium-linux.png
  e2e/tests/metrics-reducer-view.spec.ts-snapshots/12-0-3-sidebar-prefixes-selected-metric-counts-chromium-linux.png
  e2e/tests/metrics-reducer-view.spec.ts-snapshots/12-1-0-sidebar-prefixes-and-suffixes-selected-metric-counts-chromium-linux.png
  e2e/tests/metrics-reducer-view.spec.ts-snapshots/12-1-0-sidebar-prefixes-selected-metric-counts-chromium-linux.png
  e2e/tests/metrics-reducer-view.spec.ts-snapshots/metrics-reducer-default-sort-chromium-linux.png
  e2e/tests/metrics-reducer-view.spec.ts-snapshots/metrics-reducer-group-by-label-after-clear-filter-chromium-linux.png
  e2e/tests/metrics-reducer-view.spec.ts-snapshots/metrics-reducer-group-by-label-after-select-chromium-linux.png
  e2e/tests/metrics-reducer-view.spec.ts-snapshots/metrics-reducer-group-by-label-chromium-linux.png
  e2e/tests/metrics-reducer-view.spec.ts-snapshots/sidebar-prefixes-and-suffixes-selected-metric-counts-chromium-linux.png
  e2e/tests/metrics-reducer-view.spec.ts-snapshots/sidebar-prefixes-selected-metric-counts-chromium-linux.png
  package.json
  scripts/e2e-del-screenshots.sh
  scripts/e2e-gen-screenshots.sh
Labels: test

#593 chore: bump version to v1.0.8
  CHANGELOG.md
  package-lock.json
  package.json
Labels: chore

#589 docs: specify requirement to match Prometheus scrape interval in the DS configuration
  docs/sources/get-started/index.md
Labels: type/docs

#567 feat(Extensions): Update Grafana assistant extension point to use full query to generate a URL
  src/extensions/links.test.ts
  src/extensions/links.ts
  src/plugin.json
Labels: feat

#569 feat: entry point extension point for metrics drilldown from an alert rule
  src/extensions/links.test.ts
  src/extensions/links.ts
  src/plugin.json
Labels: ✨ enhancement, :potted_plant: increase adoption/consumption, feat
