Repository grafana/metrics-drilldown, pull requests merged in 2025-10, with the labels that each got.

#747 chore: cd deploys to dev
  .github/workflows/publish-dev.yml
  .github/workflows/publish.yml
Labels: chore

#755 chore: add git ref sha in CD
  .github/workflows/cd.yml
Labels: chore

#712 feat(MetricsReducer): Add recent metrics filter in the sidebar
  e2e/tests/metrics-reducer/metrics-reducer-view.spec.ts
  e2e/tests/metrics-reducer/metrics-reducer-view.spec.ts-snapshots/11-6-6-metrics-reducer-default-sort-chromium-linux.png
  e2e/tests/metrics-reducer/metrics-reducer-view.spec.ts-snapshots/11-6-6-sidebar-prefixes-and-suffixes-selected-metric-counts-chromium-linux.png
  e2e/tests/metrics-reducer/metrics-reducer-view.spec.ts-snapshots/11-6-6-sidebar-prefixes-selected-metric-counts-chromium-linux.png
  e2e/tests/metrics-reducer/metrics-reducer-view.spec.ts-snapshots/12-0-5-metrics-reducer-default-sort-chromium-linux.png
  e2e/tests/metrics-reducer/metrics-reducer-view.spec.ts-snapshots/12-0-5-sidebar-prefixes-and-suffixes-selected-metric-counts-chromium-linux.png
  e2e/tests/metrics-reducer/metrics-reducer-view.spec.ts-snapshots/12-0-5-sidebar-prefixes-selected-metric-counts-chromium-linux.png
  e2e/tests/metrics-reducer/metrics-reducer-view.spec.ts-snapshots/12-1-2-metrics-reducer-default-sort-chromium-linux.png
  e2e/tests/metrics-reducer/metrics-reducer-view.spec.ts-snapshots/12-1-2-sidebar-prefixes-and-suffixes-selected-metric-counts-chromium-linux.png
  e2e/tests/metrics-reducer/metrics-reducer-view.spec.ts-snapshots/12-1-2-sidebar-prefixes-selected-metric-counts-chromium-linux.png
  e2e/tests/metrics-reducer/metrics-reducer-view.spec.ts-snapshots/12-2-0-metrics-reducer-default-sort-chromium-linux.png
  e2e/tests/metrics-reducer/metrics-reducer-view.spec.ts-snapshots/12-2-0-sidebar-prefixes-and-suffixes-selected-metric-counts-chromium-linux.png
  e2e/tests/metrics-reducer/metrics-reducer-view.spec.ts-snapshots/12-2-0-sidebar-prefixes-selected-metric-counts-chromium-linux.png
  src/AppDataTrail/DataTrail.tsx
  src/AppDataTrail/MetricDatasourceHelper/MetricDatasourceHelper.ts
  src/MetricScene/RelatedMetrics/RelatedMetricsScene.tsx
  src/MetricsReducer/SideBar/SideBar.tsx
  src/MetricsReducer/SideBar/SideBarButton.tsx
  src/MetricsReducer/SideBar/sections/MetricsFilterSection/CheckBoxList.tsx
  src/MetricsReducer/SideBar/sections/RecentMetricsSection/RecentMetricsSection.tsx
  src/MetricsReducer/components/SceneByVariableRepeater.tsx
  src/MetricsReducer/metrics-variables/MetricsVariable.ts
  src/shared/tracking/interactions.ts
Labels: feat

#757 refactor: feplace custom flexbox CSS with Stack component in BookmarksList.tsx
  package-lock.json
  package.json
  src/MetricsReducer/SideBar/sections/BookmarksList/BookmarksList.tsx
Labels: refactor
