Repository grafana/metrics-drilldown, pull requests merged in 2025-08, with the labels that each got.

#527 feat: show list of dashboards metric is used in
  provisioning/dashboards/dashboardJson/wingman/test-dashboard-00-1754404058792.json
  provisioning/dashboards/dashboardJson/wingman/test-dashboard-02-1754403992478.json
  src/WingmanDataTrail/ListControls/MetricsSorter/MetricUsageFetcher.ts
  src/WingmanDataTrail/ListControls/MetricsSorter/MetricsSorter.tsx
  src/WingmanDataTrail/ListControls/MetricsSorter/fetchers/fetchAlertingMetrics.ts
  src/WingmanDataTrail/ListControls/MetricsSorter/fetchers/fetchDashboardMetrics.ts
  src/WingmanDataTrail/MetricVizPanel/UsageData.tsx
  src/WingmanDataTrail/MetricVizPanel/WithUsageDataPreviewPanel.tsx
Labels: feat

#595 fix: add support for panels with very small values in data
  package-lock.json
  package.json
  src/WingmanDataTrail/MetricVizPanel/panels/buildTimeseriesPanel.ts
  src/autoQuery/behaviors/ExtremeValueFilterBehavior.tsx
  src/autoQuery/buildPrometheusQuery.test.ts
  src/autoQuery/buildPrometheusQuery.ts
  src/autoQuery/components/AutoVizPanel.tsx
  src/extensions/links.ts
  src/interactions.ts
Labels: fix

#609 refactor(SceneByFrameRepeater): Allow $data to be passed to the constructor
  src/Breakdown/MetricLabelValuesList/SceneByFrameRepeater.tsx
Labels: refactor

#611 chore: Update @typescript-eslint
  package-lock.json
  package.json
Labels: chore

#610 refactor(DataTrails): Allow initializeHistograms to be called several times without creating a new API request
  src/DataTrail.tsx
Labels: refactor

#616 fix(MetricScene): Fix fatal error in an edge case where there's no data
  src/Breakdown/MetricLabelsList/LabelVizPanel.tsx
  src/services/sorting.ts
Labels: fix

#617 fix(Breakdown): Address Scene warnings
  src/Breakdown/MetricLabelValuesList/LabelValueVizPanel.tsx
Labels: fix

#594 refactor(*): Use single VizPanel across the app
  e2e/tests/metric-scene-view.spec.ts-snapshots/metric-scene-breakdown-label-single-panel-chromium-linux.png
  e2e/tests/metric-scene-view.spec.ts-snapshots/metric-scene-main-viz-chromium-linux.png
  e2e/tests/metric-scene-view.spec.ts-snapshots/metric-scene-main-viz-percentiles-chromium-linux.png
  e2e/tests/metrics-reducer-view.spec.ts
  e2e/tests/metrics-reducer-view.spec.ts-snapshots/11-6-4-metrics-reducer-default-sort-chromium-linux.png
  e2e/tests/metrics-reducer-view.spec.ts-snapshots/11-6-4-sidebar-prefixes-and-suffixes-selected-metric-counts-chromium-linux.png
  e2e/tests/metrics-reducer-view.spec.ts-snapshots/11-6-4-sidebar-prefixes-selected-metric-counts-chromium-linux.png
  e2e/tests/metrics-reducer-view.spec.ts-snapshots/12-0-3-metrics-reducer-default-sort-chromium-linux.png
  e2e/tests/metrics-reducer-view.spec.ts-snapshots/12-0-3-sidebar-prefixes-and-suffixes-selected-metric-counts-chromium-linux.png
  e2e/tests/metrics-reducer-view.spec.ts-snapshots/12-0-3-sidebar-prefixes-selected-metric-counts-chromium-linux.png
  e2e/tests/metrics-reducer-view.spec.ts-snapshots/12-1-0-metrics-reducer-default-sort-chromium-linux.png
  e2e/tests/metrics-reducer-view.spec.ts-snapshots/12-1-0-sidebar-prefixes-and-suffixes-selected-metric-counts-chromium-linux.png
  e2e/tests/metrics-reducer-view.spec.ts-snapshots/12-1-0-sidebar-prefixes-selected-metric-counts-chromium-linux.png
  e2e/tests/metrics-reducer-view.spec.ts-snapshots/metric-list-with-all-types-chromium-linux.png
  e2e/tests/metrics-reducer-view.spec.ts-snapshots/metric-scene-main-viz-go-goroutines-chromium-linux.png
  e2e/tests/metrics-reducer-view.spec.ts-snapshots/metric-scene-main-viz-go-memstats-heap-inuse-bytes-chromium-linux.png
  e2e/tests/metrics-reducer-view.spec.ts-snapshots/metric-scene-main-viz-prometheus-http-requests-total-chromium-linux.png
  e2e/tests/metrics-reducer-view.spec.ts-snapshots/metric-scene-main-viz-pyroscope-build-info-chromium-linux.png
  e2e/tests/metrics-reducer-view.spec.ts-snapshots/metric-scene-main-viz-up-chromium-linux.png
  e2e/tests/metrics-reducer-view.spec.ts-snapshots/metrics-reducer-default-sort-chromium-linux.png
  src/Breakdown/MetricLabelValuesList/LabelValueVizPanel.tsx
  src/Breakdown/MetricLabelValuesList/MetricLabelValuesList.tsx
  src/Breakdown/MetricLabelsList/LabelVizPanel.tsx
  src/Breakdown/MetricLabelsList/MetricLabelsList.tsx
  src/GmdVizPanel/EventPanelTypeChanged.ts
  src/GmdVizPanel/GmdVizPanel.tsx
  src/GmdVizPanel/GmdVizPanelVariantSelector.tsx
  src/GmdVizPanel/buildQueryExpression.ts
  src/GmdVizPanel/heatmap/buildHeatmapPanel.ts
  src/GmdVizPanel/heatmap/getHeatmapQueryRunnerParams.ts
  src/GmdVizPanel/heatmap/isHistogramMetric.ts
  src/GmdVizPanel/percentiles/buildPercentilesPanel.ts
  src/GmdVizPanel/percentiles/getPercentilesQueryRunnerParams.ts
  src/GmdVizPanel/statushistory/buildStatushistoryPanel.ts
  src/GmdVizPanel/statushistory/getStatushistoryQueryRunnerParams.ts
  src/GmdVizPanel/statushistory/isUpDownMetric.ts
  src/GmdVizPanel/timeseries/buildTimeseriesPanel.ts
  src/GmdVizPanel/timeseries/getTimeseriesQueryRunnerParams.ts
  src/GmdVizPanel/timeseries/isRateQuery.ts
  src/GmdVizPanel/units/getUnit.spec.ts
  src/GmdVizPanel/units/getUnit.ts
  src/Menu/PanelMenu.tsx
  src/MetricActionBar.tsx
  src/MetricGraphScene.tsx
  src/MetricScene.tsx
  src/WingmanDataTrail/GroupBy/MetricsGroupByRow.tsx
  src/WingmanDataTrail/MetricVizPanel/WithUsageDataPreviewPanel.tsx
  src/WingmanDataTrail/MetricsList/MetricsList.tsx
Labels: refactor

#628 ci(EndToEnd): Update support for Grafana v12.1.1
  docs/end-to-end-testing.md
  e2e/config/grafana-versions-supported.ts
  e2e/tests/metric-scene-view.spec.ts-snapshots/12-1-0-metric-scene-breakdown-all-panels-list-chromium-linux.png
  e2e/tests/metric-scene-view.spec.ts-snapshots/12-1-1-metric-scene-breakdown-all-panels-list-chromium-linux.png
  e2e/tests/metrics-reducer-view.spec.ts-snapshots/12-1-0-metrics-reducer-default-sort-chromium-linux.png
  e2e/tests/metrics-reducer-view.spec.ts-snapshots/12-1-0-metrics-reducer-scopes-filters-applied-chromium-linux.png
  e2e/tests/metrics-reducer-view.spec.ts-snapshots/12-1-1-metrics-reducer-default-sort-chromium-linux.png
  e2e/tests/metrics-reducer-view.spec.ts-snapshots/12-1-1-metrics-reducer-scopes-filters-applied-chromium-linux.png
  e2e/tests/metrics-reducer-view.spec.ts-snapshots/12-1-1-sidebar-prefixes-and-suffixes-selected-metric-counts-chromium-linux.png
  e2e/tests/metrics-reducer-view.spec.ts-snapshots/12-1-1-sidebar-prefixes-selected-metric-counts-chromium-linux.png
  scripts/e2e-del-all-screenshots.sh
  scripts/e2e-gen-all-screenshots.sh
Labels: ci

#629 fix(links): use template vars in links
  src/extensions/links.test.ts
  src/extensions/links.ts
Labels: fix

#633 refactor: prepare for embedded metrics reducer
  src/TrailStore/TrailStore.test.ts
  src/WingmanDataTrail/MetricsVariables/computeRulesGroups.ts
  src/autoQuery/behaviors/ExtremeValueFilterBehavior.tsx
  src/exposedComponents/LabelBreakdown/LabelBreakdown.tsx
  src/extensions/links.ts
  src/mocks/datasource.ts
  src/stubs/dataSourceStub.ts
  src/types/language-provider/v11-6-x.ts
  src/types/language-provider/v12-0-0.ts
  src/utils/utils.promql.ts
  src/utils/utils.timerange.ts
Labels: refactor

#642 chore: Update Playwright to v1.55.0
  e2e/docker/Dockerfile.playwright
  package-lock.json
  package.json
Labels: chore

#640 chore: capture extension point id for initializing app
  src/App/useReportAppInitialized.ts
  src/interactions.ts
Labels: chore

#645 perf(*): Improve native histograms detection
  src/DataTrail.tsx
  src/autoQuery/components/AutoVizPanel.tsx
  src/helpers/MetricDataSourceHelper.test.ts
  src/helpers/MetricDatasourceHelper.ts
Labels: perf

#647 perf(*): Improve Native Histograms detection
  src/DataTrail.tsx
  src/GmdVizPanel/GmdVizPanel.tsx
  src/RelatedMetricsScene/RelatedMetricsScene.tsx
  src/WingmanDataTrail/MetricsReducer.tsx
  src/helpers/MetricDatasourceHelper.ts
  src/mocks/datasource.ts
Labels: perf

#648 refactor(NativeHistograms): Slight improvement and unit tests
  src/helpers/MetricDatasourceHelper.spec.ts
  src/helpers/MetricDatasourceHelper.ts
  src/mocks/datasource.ts
Labels: refactor

#653 refactor(UserPreferences): Rename to UserStorage
  jest.config.js
  src/App/App.tsx
  src/Breakdown/MetricLabelValuesList/SortBySelector.tsx
  src/GmdVizPanel/components/ConfigurePanelAction.tsx
  src/GmdVizPanel/components/ConfigurePanelForm/ConfigurePanelForm.tsx
  src/GmdVizPanel/config/getPreferredConfigForMetric.ts
  src/MetricsDrilldownDataSourceVariable.ts
  src/TrailStore/TrailStore.test.ts
  src/TrailStore/TrailStore.ts
  src/UserPreferences/userStorage.ts
  src/WingmanDataTrail/ListControls/MetricsSorter/MetricsSorter.test.tsx
  src/WingmanDataTrail/ListControls/MetricsSorter/MetricsSorter.tsx
  src/interactions.ts
  src/mocks/userStorage.ts
Labels: refactor

#652 fix(NativeHistograms): Fix queries
  src/Breakdown/GroupByVariable.tsx
  src/GmdVizPanel/types/heatmap/__test__/getHeatmapQueryRunnerParams.spec.ts
  src/GmdVizPanel/types/heatmap/getHeatmapQueryRunnerParams.ts
  src/GmdVizPanel/types/percentiles/__test__/getPercentilesQueryRunnerParams.spec.ts
  src/GmdVizPanel/types/percentiles/getPercentilesQueryRunnerParams.ts
Labels: fix

#657 fix(*): Fix queries for label values containing special chars (like the equal sign)
  src/DataTrail.tsx
  src/GmdVizPanel/__test__/buildQueryExpression.spec.ts
  src/GmdVizPanel/buildQueryExpression.ts
  src/GmdVizPanel/types/heatmap/__test__/getHeatmapQueryRunnerParams.spec.ts
  src/GmdVizPanel/types/percentiles/__test__/getPercentilesQueryRunnerParams.spec.ts
  src/GmdVizPanel/types/stat/__test__/getStatQueryRunnerParams.spec.ts
  src/GmdVizPanel/types/statushistory/__test__/getStatushistoryQueryRunnerParams.spec.ts
  src/GmdVizPanel/types/timeseries/__test__/getTimeseriesQueryRunnerParams.spec.ts
Labels: fix

#659 fix(*): Prevent flickering
  src/MetricGraphScene.tsx
  src/WingmanDataTrail/MetricsReducer.tsx
Labels: fix

#661 chore(LayoutSwitcher): Track layout changes
  src/WingmanDataTrail/ListControls/LayoutSwitcher.tsx
  src/interactions.ts
Labels: chore

#660 refactor(*): Finalize unique VizPanel
  src/Breakdown/GroupByVariable.tsx
  src/Breakdown/MetricLabelValuesList/LabelValueVizPanel.tsx
  src/Breakdown/MetricLabelValuesList/MetricLabelValuesList.tsx
  src/Breakdown/MetricLabelsList/LabelVizPanel.tsx
  src/Breakdown/MetricLabelsList/MetricLabelsList.tsx
  src/Breakdown/MetricLabelsList/behaviors/publishTimeseriesData.ts
  src/Breakdown/MetricLabelsList/behaviors/syncYAxis.ts
  src/Breakdown/MetricLabelsList/events/EventTimeseriesDataReceived.ts
  src/Breakdown/MetricLabelsList/transformations/sliceSeries.ts
  src/GmdVizPanel/GmdVizPanel.tsx
  src/GmdVizPanel/types/heatmap/buildHeatmapPanel.ts
  src/GmdVizPanel/types/percentiles/buildPercentilesPanel.ts
  src/GmdVizPanel/types/stat/buildStatPanel.ts
  src/GmdVizPanel/types/statushistory/buildStatushistoryPanel.ts
  src/GmdVizPanel/types/timeseries/addCardinalityInfo.ts
  src/GmdVizPanel/types/timeseries/buildTimeseriesPanel.ts
  src/MetricGraphScene.tsx
Labels: refactor

#662 fix(links): escape value delimiters the scenes way
  src/extensions/links.test.ts
  src/extensions/links.ts
Labels: fix
